export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_SHOW_LOADER = "SET_SHOW_LOADER";
export const SET_PAGINATED_USERS = "SET_PAGINATED_USERS";
export const SET_FETCHED_USERS = "SET_FETCHED_USERS";